spring.application.name=Application

# H2 database configuration --> in memory database as mentioned in the question
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
spring.h2.console.enabled=true

logging.level.org.hibernate.SQL=WARN

# Server port configuration
server.port=3000